Fixes for admin script

diff --git a/rebar3_riak_core_admin_runner b/rebar3_riak_core_admin_runner
--- a/rebar3_riak_core_admin_runner
+++ b/rebar3_riak_core_admin_runner
@@ -12,62 +12,147 @@ fi
 unset POSIX_SHELL # clear it so if we invoke other scripts, they run as ksh as well
 
 
-RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)
-RUNNER_SCRIPT=${0##*/}
+SCRIPT=$(readlink $0 || true)
+if [ -z $SCRIPT ]; then
+    SCRIPT=$0
+fi;
 
-RUNNER_BASE_DIR=${RUNNER_SCRIPT_DIR%/*}
-RUNNER_ETC_DIR=$RUNNER_BASE_DIR/etc
-RUNNER_LOG_DIR=$RUNNER_BASE_DIR/log
 
-RUNNER_USER=
+SCRIPT_DIR="$(cd `dirname "$SCRIPT"` && pwd -P)"
+RELEASE_ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
+REL_NAME="{{ release_name }}"
+CUTTLEFISH_CONF="{{ release_name }}.conf"
+REL_VSN="{{ rel_vsn }}"
+ERTS_VSN="{{ erts_vsn }}"
+CODE_LOADING_MODE="${CODE_LOADING_MODE:-embedded}"
+REL_DIR="$RELEASE_ROOT_DIR/releases/$REL_VSN"
+ERL_OPTS="{{ erl_opts }}"
+RUNNER_LOG_DIR="${RUNNER_LOG_DIR:-$RELEASE_ROOT_DIR/log}"
+RUNNER_BASE_DIR=$RELEASE_ROOT_DIR
+RUNNER_ETC_DIR="${RUNNER_ETC_DIR:-$RELEASE_ROOT_DIR/etc}"
 
-WHOAMI=$(whoami)
-
-# Make sure this script is running as the appropriate user
-if ([ "$RUNNER_USER" ] && [ "x$WHOAMI" != "x$RUNNER_USER" ]); then
-    type sudo > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
-        echo "sudo doesn't appear to be installed and your EUID isn't $RUNNER_USER" 1>&2
-        exit 1
-    fi
-    echo "Attempting to restart script through sudo -H -u $RUNNER_USER" >&2
-    exec sudo -H -u $RUNNER_USER -i $RUNNER_SCRIPT_DIR/$RUNNER_SCRIPT $@
-fi
-
-# Make sure CWD is set to runner base dir
-cd $RUNNER_BASE_DIR
-
-# Extract the target node name from node.args
-NAME_ARG=`egrep "^ *-s?name" $RUNNER_ETC_DIR/vm.args`
-if [ -z "$NAME_ARG" ]; then
-    echo "vm.args needs to have either -name or -sname parameter."
-    exit 1
-fi
-
-# Learn how to specify node name for connection from remote nodes
-echo "$NAME_ARG" | grep '^-sname' > /dev/null 2>&1
-if [ "X$?" = "X0" ]; then
-    NAME_PARAM="-sname"
-    NAME_HOST=""
-else
-    NAME_PARAM="-name"
-    echo "$NAME_ARG" | grep '@.*' > /dev/null 2>&1
-    if [ "X$?" = "X0" ]; then
-        NAME_HOST=`echo "${NAME_ARG}" | sed -e 's/.*\(@.*\)$/\1/'`
+find_erts_dir() {
+    __erts_dir="$RELEASE_ROOT_DIR/erts-$ERTS_VSN"
+    if [ -d "$__erts_dir" ]; then
+        ERTS_DIR="$__erts_dir";
+        ROOTDIR="$RELEASE_ROOT_DIR"
     else
-        NAME_HOST=""
+        __erl="$(which erl)"
+        code="io:format(\"~s\", [code:root_dir()]), halt()."
+        __erl_root="$("$__erl" -noshell -eval "$code")"
+        ERTS_DIR="$__erl_root/erts-$ERTS_VSN"
+        ROOTDIR="$__erl_root"
+    fi
+}
+
+# Get node pid
+relx_get_pid() {
+    if output="$(relx_nodetool rpcterms os getpid)"
+    then
+        echo "$output" | sed -e 's/"//g'
+        return 0
+    else
+        echo "$output"
+        return 1
+    fi
+}
+
+relx_get_longname() {
+    id="longname$(relx_gen_id)-${NAME}"
+    "$BINDIR/erl" -boot start_clean -eval 'io:format("~s~n", [node()]), halt()' -noshell -name $id | sed -e 's/.*@//g'
+}
+
+# Connect to a remote node
+relx_rem_sh() {
+    # Generate a unique id used to allow multiple remsh to the same node
+    # transparently
+    id="remsh$(relx_gen_id)-${NAME}"
+
+    # Get the node's ticktime so that we use the same thing.
+    TICKTIME="$(relx_nodetool rpcterms net_kernel get_net_ticktime)"
+
+    # Setup remote shell command to control node
+    exec "$BINDIR/erl" "$NAME_TYPE" "$id" -remsh "$NAME" -boot start_clean \
+         -boot_var ERTS_LIB_DIR "$ERTS_LIB_DIR" \
+         -setcookie "$COOKIE" -hidden -kernel net_ticktime $TICKTIME
+}
+
+# Generate a random id
+relx_gen_id() {
+    od -X -N 4 /dev/urandom | head -n1 | awk '{print $2}'
+}
+
+# Control a node
+relx_nodetool() {
+    command="$1"; shift
+
+    "$ERTS_DIR/bin/escript" "$ROOTDIR/bin/nodetool" "$NAME_TYPE" "$NAME" \
+                                -setcookie "$COOKIE" "$command" $@
+}
+
+# Run an escript in the node's environment
+relx_escript() {
+    shift; scriptpath="$1"; shift
+    export RELEASE_ROOT_DIR
+
+    "$ERTS_DIR/bin/escript" "$ROOTDIR/$scriptpath" $@
+}
+
+# Output a start command for the last argument of run_erl
+relx_start_command() {
+    printf "exec \"%s\" \"%s\"" "$RELEASE_ROOT_DIR/bin/$REL_NAME" \
+           "$START_OPTION"
+}
+
+# Make sure log directory exists
+mkdir -p "$RUNNER_LOG_DIR"
+
+# Use $CWD/sys.config if exists, otherwise releases/VSN/sys.config
+if [ -z "$NAME_ARG" ]; then
+    NODENAME=`egrep '^[ \t]*nodename[ \t]*=[ \t]*' $RUNNER_ETC_DIR/$CUTTLEFISH_CONF 2> /dev/null | tail -n 1 | cut -d = -f 2`
+    if [ -z "$NODENAME" ]; then
+        echo "vm.args needs to have a -name parameter."
+        echo "  -sname is not supported."
+        exit 1
+    else
+        NAME_TYPE="-name"
+        NAME="${NODENAME# *}"
     fi
 fi
+
+PIPE_DIR="${PIPE_DIR:-/tmp/erl_pipes/$NAME/}"
 
 # Extract the target cookie
-COOKIE_ARG=`grep '\-setcookie' $RUNNER_ETC_DIR/vm.args`
+#COOKIE_ARG=`grep -e '-setcookie' $RUNNER_ETC_DIR/vm.args`
 if [ -z "$COOKIE_ARG" ]; then
-    echo "vm.args needs to have a -setcookie parameter."
+    COOKIE=`egrep '^[ \t]*distributed_cookie[ \t]*=[ \t]*' $RUNNER_ETC_DIR/$CUTTLEFISH_CONF 2> /dev/null | cut -d = -f 2 | tr -d ' '`
+    if [ -z "$COOKIE" ]; then
+        echo "vm.args needs to have a -setcookie parameter."
+        exit 1
+    else
+        COOKIE_ARG="-setcookie $COOKIE"
+    fi
+fi
+
+find_erts_dir
+export ROOTDIR="$RELEASE_ROOT_DIR"
+export BINDIR="$ERTS_DIR/bin"
+export EMU="beam"
+export PROGNAME="erl"
+export LD_LIBRARY_PATH="$ERTS_DIR/lib:$LD_LIBRARY_PATH"
+ERTS_LIB_DIR="$ERTS_DIR/../lib"
+CUTTLEFISHCMD="$ERTS_DIR/bin/escript $RUNNER_BASE_DIR/bin/cuttlefish"
+
+cd "$ROOTDIR"
+
+if CUTTLEFISH_CONFIG=$($CUTTLEFISHCMD -e $RUNNER_ETC_DIR -d $RUNNER_BASE_DIR/generated.conf -s $RUNNER_BASE_DIR/share/schema/ -c $RUNNER_ETC_DIR/$CUTTLEFISH_CONF)
+then
+    CONFIG_FILES="$CUTTLEFISH_CONFIG"
+else
+    echo "Cuttlefish failed! Oh no!"
     exit 1
 fi
 
-# Identify the script name
-SCRIPT=`basename $0`
 
 # Parse out release and erts info
 START_ERL=`cat $RUNNER_BASE_DIR/releases/start_erl.data`
@@ -84,8 +169,7 @@ NODETOOL="$ESCRIPT $NODETOOL $NAME_ARG $COOKIE_ARG"
 ensure_node_running()
 {
     # Make sure the local node IS running
-    RES=`$NODETOOL ping`
-    if [ "$RES" != "pong" ]; then
+    if ! relx_nodetool "ping"; then
         echo "Node is not running!"
         exit 1
     fi
@@ -100,15 +184,15 @@ cluster_admin()
                 exit 1
             fi
             ensure_node_running
-            $NODETOOL rpc {{name}}_console staged_join "$2"
+            relx_nodetool rpc {{ release_name }}_console staged_join "$2"
             ;;
         leave)
             if [ $# -eq 1 ]; then
                 ensure_node_running
-                $NODETOOL rpc riak_core_console stage_leave
+                relx_nodetool rpc riak_core_console stage_leave
             elif [ $# -eq 2 ]; then
                 ensure_node_running
-                $NODETOOL rpc riak_core_console stage_leave "$2"
+                relx_nodetool rpc riak_core_console stage_leave "$2"
             else
                 echo "Usage: $SCRIPT cluster leave [<node>]"
                 exit 1
@@ -120,7 +204,7 @@ cluster_admin()
                 exit 1
             fi
             ensure_node_running
-            $NODETOOL rpc riak_core_console stage_remove "$2"
+            relx_nodetool rpc riak_core_console stage_remove "$2"
             ;;
         replace)
             if [ $# -ne 3 ]; then
@@ -128,7 +212,7 @@ cluster_admin()
                 exit 1
             fi
             ensure_node_running
-            $NODETOOL rpc riak_core_console stage_replace "$2" "$3"
+            relx_nodetool rpc riak_core_console stage_replace "$2" "$3"
             ;;
         force-replace)
             if [ $# -ne 3 ]; then
@@ -136,19 +220,19 @@ cluster_admin()
                 exit 1
             fi
             ensure_node_running
-            $NODETOOL rpc riak_core_console stage_force_replace "$2" "$3"
+            relx_nodetool rpc riak_core_console stage_force_replace "$2" "$3"
             ;;
         plan)
             ensure_node_running
-            $NODETOOL rpc riak_core_console print_staged
+            relx_nodetool rpc riak_core_console print_staged
             ;;
         commit)
             ensure_node_running
-            $NODETOOL rpc riak_core_console commit_staged
+            relx_nodetool rpc riak_core_console commit_staged
             ;;
         clear)
             ensure_node_running
-            $NODETOOL rpc riak_core_console clear_staged
+            relx_nodetool rpc riak_core_console clear_staged
             ;;
         *)
             echo "\
@@ -189,14 +273,8 @@ case "$1" in
             exit 1
         fi
 
-        RES=`$NODETOOL ping`
-        if [ "$RES" != "pong" ]; then
-            echo "Node is not running!"
-            exit 1
-        fi
-
-        shift
-        $NODETOOL rpc {{name}}_console down $@
+        ensure_node_running
+        relx_nodetool rpc {{ release_name }}_console down $@
         ;;
 
      ringready)
@@ -205,15 +283,8 @@ case "$1" in
             exit 1
         fi
 
-        # Make sure the local node IS running
-        RES=`$NODETOOL ping`
-        if [ "$RES" != "pong" ]; then
-            echo "Node is not running!"
-            exit 1
-        fi
-        shift
-
-        $NODETOOL rpc {{name}}_console ringready $@
+        ensure_node_running
+        relx_nodetool rpc {{ release_name }}_console ringready ''
         ;;
 
     member[_-]status)
@@ -222,15 +293,8 @@ case "$1" in
             exit 1
         fi
 
-        # Make sure the local node IS running
-        RES=`$NODETOOL ping`
-        if [ "$RES" != "pong" ]; then
-            echo "Node is not running!"
-            exit 1
-        fi
-        shift
-
-        $NODETOOL rpc riak_core_console member_status $@
+        ensure_node_running
+        relx_nodetool rpc riak_core_console member_status ''
         ;;
 
     ring[_-]status)
@@ -239,19 +303,12 @@ case "$1" in
             exit 1
         fi
 
-        # Make sure the local node IS running
-        RES=`$NODETOOL ping`
-        if [ "$RES" != "pong" ]; then
-            echo "Node is not running!"
-            exit 1
-        fi
-        shift
-
-        $NODETOOL rpc riak_core_console ring_status $@
+        ensure_node_running
+        relx_nodetool rpc riak_core_console ring_status ''
         ;;
 
     services)
-        $NODETOOL rpcterms riak_core_node_watcher services ''
+        relx_nodetool rpcterms riak_core_node_watcher services ''
         ;;
 
     wait[_-]for[_-]service)
